In [46]:
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None

In [5]:
csv_sep = '|'

In [3]:
metrics = pd.read_csv('metrics.csv', sep = csv_sep)
metrics.head()

                   bucket    var                                         label
0  Segment Classification  SEG01       Typing Tool Classification: Family Time
1  Segment Classification  SEG02  Typing Tool Classification: Romantic Getaway
2  Segment Classification  SEG03        Typing Tool Classification: Well-being
3  Segment Classification  SEG04       Typing Tool Classification: Rest and Go
4  Segment Classification  SEG05   Typing Tool Classification: Social Identity

In [4]:
df = pd.read_csv('FlatTest_Full.csv', sep = csv_sep)
df.head()

,Weight_Completes,Respondent_ID,Country,S3_DV,TravelAssignment,T4a,T5,O26D,O26D2_2nd,O26D2_3rd,...,BTCF,BPSF,WBDIM,RGDIM,FTDIM,SBDIM,MBPDIM,BPDIM,BBIDIM,SDIM
0,0.498927,1,4,1,3,5,2,60,61,75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.545428,2,4,4,3,4,2,146,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.822232,3,3,3,3,3,8,185,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.853067,4,3,4,1,5,1,112,54,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.982030,5,3,4,3,3,1,62,113,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
filt_ban = pd.read_csv('Filters.csv', sep = csv_sep)
filt_ban.head()

     group      var  filter_val           label filter banner
0  Country  Country         NaN   All Countries   True   True
1  Country  Country           1   United States   True   True
2  Country  Country           2  United Kingdom   True   True
3  Country  Country           3           China   True   True
4  Country  Country           4         Germany   True   True

In [32]:
filt_ban_vars = ['Weight_Completes', 'Respondent_ID']
filt_ban_vars += filt_ban['var'].unique().tolist()

In [27]:
filt_ban_vars

['Country',
 'S3_DV',
 'SEG01',
 'SEG02',
 'SEG03',
 'SEG04',
 'SEG05',
 'SEG06',
 'Weight_Completes',
 'Respondent_ID']

In [33]:
respondents = df[filt_ban_vars]

In [34]:
respondents

,Weight_Completes,Respondent_ID,Country,S3_DV,SEG01,SEG02,SEG03,SEG04,SEG05,SEG06
0,0.498927,1,4,1,0,1,0,0,0,0
1,0.545428,2,4,4,1,0,0,0,0,0
2,0.822232,3,3,3,0,0,0,0,0,0
3,1.853067,4,3,4,1,0,0,0,0,0
4,0.982030,5,3,4,1,0,0,0,0,0
5,0.736577,6,3,2,1,0,0,0,0,0
6,0.390348,7,3,2,1,0,0,0,0,0
7,0.301840,8,5,2,0,0,0,1,0,0
8,0.770703,9,5,2,0,0,0,1,0,0
9,0.253127,10,4,2,0,0,0,0,0,1
10,0.718764,11,1,3,0,0,1,0,0,0
11,0.632129,12,1,4,1,0,0,0,0,0
12,0.521031,13,4,4,0,1,0,0,0,0
13,1.299590,14,1,4,0,0,1,0,0,0
14,0.802110,15,3,2,0,0,0,0,0,1
15,0.390348,16,3,2,1,0,0,0,0,0
16,0.639808,17,4,4,0,0,0,0,1,0
17,0.531259,18,4,4,0,0,1,0,0,0
18,1.903282,19,1,5,0,0,0,1,0,0
19,1.220512,20,1,5,0,1,0,0,0,0
20,3.127948,21,3,2,0,0,0,0,0,0
21,0.943285,22,3,2,0,0,0,0,0,0
22,0.721651,23,5,4,0,0,0,1,0,0
23,0.770703,24,5,4,0,0,1,0,0,0
24,0.943285,25,3,2,0,0,0,0,0,0
25,0.770703,26,5,3,0,0,0,1,0,0
26,0.699174,27,3,3,0,0,0,0,0,1
27,0.395786,28,3,3,0,0,0,0,0,1
28,0.572154,29,1,6,0,1,0,0,0,0
29,2.796047,30,4,5,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
9960,0.301840,9961,5,6,0,0,1,0,0,0
9961,0.770703,9962,5,6,0,0,0,1,0,0
9962,0.770703,9963,5,6,0,0,0,1,0,0
9963,0.770703,9964,5,6,0,0,0,1,0,0
9964,1.245477,9965,5,6,1,0,0,0,0,0
9965,1.245477,9966,5,4,1,0,0,0,0,0
9966,0.721651,9967,5,2,0,1,0,0,0,0
9967,0.770703,9968,5,2,0,1,0,0,0,0
9968,0.683885,9969,5,4,0,0,0,0,0,1
9969,0.770703,9970,5,4,0,0,0,1,0,0
9970,1.245477,9971,5,2,0,0,0,0,0,0
9971,3.554724,9972,5,6,0,0,1,0,0,0
9972,0.721651,9973,5,5,0,0,0,1,0,0
9973,0.739277,9974,5,5,1,0,0,0,0,0
9974,0.770703,9975,5,4,0,0,0,1,0,0
9975,1.245477,9976,5,3,0,1,0,0,0,0
9976,1.245477,9977,5,6,0,1,0,0,0,0
9977,0.721651,9978,5,3,0,0,0,1,0,0
9978,0.286044,9979,5,3,0,0,0,0,0,1
9979,0.770703,9980,5,3,0,0,0,1,0,0
9980,1.245477,9981,5,2,0,1,0,0,0,0
9981,0.289533,9982,5,4,1,0,0,0,0,0
9982,0.739277,9983,5,4,1,0,0,0,0,0
9983,0.683885,9984,5,5,0,0,0,0,0,1
9984,0.770703,9985,5,5,0,0,0,1,0,0
9985,0.770703,9986,5,5,0,0,0,1,0,0
9986,1.245477,9987,5,3,0,1,0,0,0,0
9987,0.721651,9988,5,6,0,0,0,1,0,0
9988,0.770703,9989,5,6,0,0,0,1,0,0
9989,0.739277,9990,5,6,0,0,0,0,0,0

In [53]:
respondents['Project_ID'] = 123456

,Weight_Completes,Respondent_ID,Country,S3_DV,SEG01,SEG02,SEG03,SEG04,SEG05,SEG06,Project_ID
0,0.498927,1,4,1,0,1,0,0,0,0,123456
1,0.545428,2,4,4,1,0,0,0,0,0,123456
2,0.822232,3,3,3,0,0,0,0,0,0,123456
3,1.853067,4,3,4,1,0,0,0,0,0,123456
4,0.982030,5,3,4,1,0,0,0,0,0,123456
5,0.736577,6,3,2,1,0,0,0,0,0,123456
6,0.390348,7,3,2,1,0,0,0,0,0,123456
7,0.301840,8,5,2,0,0,0,1,0,0,123456
8,0.770703,9,5,2,0,0,0,1,0,0,123456
9,0.253127,10,4,2,0,0,0,0,0,1,123456
10,0.718764,11,1,3,0,0,1,0,0,0,123456
11,0.632129,12,1,4,1,0,0,0,0,0,123456
12,0.521031,13,4,4,0,1,0,0,0,0,123456
13,1.299590,14,1,4,0,0,1,0,0,0,123456
14,0.802110,15,3,2,0,0,0,0,0,1,123456
15,0.390348,16,3,2,1,0,0,0,0,0,123456
16,0.639808,17,4,4,0,0,0,0,1,0,123456
17,0.531259,18,4,4,0,0,1,0,0,0,123456
18,1.903282,19,1,5,0,0,0,1,0,0,123456
19,1.220512,20,1,5,0,1,0,0,0,0,123456
20,3.127948,21,3,2,0,0,0,0,0,0,123456
21,0.943285,22,3,2,0,0,0,0,0,0,123456
22,0.721651,23,5,4,0,0,0,1,0,0,123456
23,0.770703,24,5,4,0,0,1,0,0,0,123456
24,0.943285,25,3,2,0,0,0,0,0,0,123456
25,0.770703,26,5,3,0,0,0,1,0,0,123456
26,0.699174,27,3,3,0,0,0,0,0,1,123456
27,0.395786,28,3,3,0,0,0,0,0,1,123456
28,0.572154,29,1,6,0,1,0,0,0,0,123456
29,2.796047,30,4,5,0,1,0,0,0,0,123456
...,...,...,...,...,...,...,...,...,...,...,...
9960,0.301840,9961,5,6,0,0,1,0,0,0,123456
9961,0.770703,9962,5,6,0,0,0,1,0,0,123456
9962,0.770703,9963,5,6,0,0,0,1,0,0,123456
9963,0.770703,9964,5,6,0,0,0,1,0,0,123456
9964,1.245477,9965,5,6,1,0,0,0,0,0,123456
9965,1.245477,9966,5,4,1,0,0,0,0,0,123456
9966,0.721651,9967,5,2,0,1,0,0,0,0,123456
9967,0.770703,9968,5,2,0,1,0,0,0,0,123456
9968,0.683885,9969,5,4,0,0,0,0,0,1,123456
9969,0.770703,9970,5,4,0,0,0,1,0,0,123456
9970,1.245477,9971,5,2,0,0,0,0,0,0,123456
9971,3.554724,9972,5,6,0,0,1,0,0,0,123456
9972,0.721651,9973,5,5,0,0,0,1,0,0,123456
9973,0.739277,9974,5,5,1,0,0,0,0,0,123456
9974,0.770703,9975,5,4,0,0,0,1,0,0,123456
9975,1.245477,9976,5,3,0,1,0,0,0,0,123456
9976,1.245477,9977,5,6,0,1,0,0,0,0,123456
9977,0.721651,9978,5,3,0,0,0,1,0,0,123456
9978,0.286044,9979,5,3,0,0,0,0,0,1,123456
9979,0.770703,9980,5,3,0,0,0,1,0,0,123456
9980,1.245477,9981,5,2,0,1,0,0,0,0,123456
9981,0.289533,9982,5,4,1,0,0,0,0,0,123456
9982,0.739277,9983,5,4,1,0,0,0,0,0,123456
9983,0.683885,9984,5,5,0,0,0,0,0,1,123456
9984,0.770703,9985,5,5,0,0,0,1,0,0,123456
9985,0.770703,9986,5,5,0,0,0,1,0,0,123456
9986,1.245477,9987,5,3,0,1,0,0,0,0,123456
9987,0.721651,9988,5,6,0,0,0,1,0,0,123456
9988,0.770703,9989,5,6,0,0,0,1,0,0,123456
9989,0.739277,9990,5,6,0,0,0,0,0,0,123456

In [57]:
respondents.to_json('respondents.json', orient = "records")